#ifndef VERSION_H_
#define VERSION_H_


#define HTTP2XIC_V_EDITION 	20160702
#define HTTP2XIC_V_REVISION	20170215
#define HTTP2XIC_V_RELEASE 	2200
#define HTTP2XIC_VERSION	XS_TOSTR(HTTP2XIC_V_EDITION)"."XS_TOSTR(HTTP2XIC_V_REVISION)"."XS_TOSTR(HTTP2XIC_V_RELEASE)


#endif
