#ifndef VERSION_H_
#define VERSION_H_


#define HTTP2XIC_V_EDITION 	160702
#define HTTP2XIC_V_REVISION	170614
#define HTTP2XIC_V_RELEASE 	18
#define HTTP2XIC_VERSION	XS_TOSTR(HTTP2XIC_V_EDITION) "." XS_TOSTR(HTTP2XIC_V_REVISION) "." XS_TOSTR(HTTP2XIC_V_RELEASE)


#endif
